# Workflow para build e teste de projeto Java com Maven
# Cache de dependências para acelerar execuções
# Mais info: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd Pipeline_aula
          mvn clean install -DskipTests
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar file
          path: Pipeline_aula/target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd Pipeline_aula
          mvn clean test site
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test report
          path: Pipeline_aula/target/site/

  notification:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notification
        run: sh scripts/sendEmail.sh
