name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd Pipeline_aula
        mvn clean install -DskipTests

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar file
        path: Pipeline_aula/target/*.jar

  test:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd Pipeline_aula
        mvn clean test site

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: test report
        path: Pipeline_aula/target/site/

  notification:

    needs: [build, test]   # <-- depende dos dois
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sh scripts/install.sh

    - name: Send Notification Email
      env:
        EMAIL_TO: ${{ secrets.EMAIL_TO }}   # <-- secret configurado no GitHub
      run: sh scripts/sendEmail.sh
