# Workflow para build e teste de projeto Java com Maven
# Cache de dependências para acelerar execuções
# Mais info: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd Pipeline_aula
          mvn clean install -DskipTests
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar file
          path: Pipeline_aula/target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd Pipeline_aula
          mvn clean test site
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test report
          path: Pipeline_aula/target/site/

  notification:
    needs: build   # roda em paralelo com "test"
    runs-on: ubuntu-latest
    env:
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
    steps:
      - uses: actions/checkout@v4
      - name: Install mailutils
        run: |
          sudo apt-get update
          sudo apt-get install -y mailutils
      - name: Notification
        run: |
          if [ "${{ needs.build.result }}" == "success" ] && [ "${{ needs.test.result }}" == "success" ]; then
            echo "Pipeline executado com sucesso!" | mail -s "Pipeline Status" $EMAIL_TO
          else
            echo "Pipeline falhou em algum estágio." | mail -s "Pipeline Status" $EMAIL_TO
          fi
